title: Minha página de anotações
description: Minhas notas e observações de estudo sobre diversos temas de tecnologia. Esta página está em contante evolução.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight